### ISSUE TITLE
Handle commands on mention

### ISSUE THREAD

**Issue by dhvcc** [z164/telegram-bsuir-schedule#3]
Может стоит делать обработку команд только по упоминанию? Команды могут путаться с другими ботами

**Comment by z164** [comment]
Триггером команд являются регулярные выражения, которые ожидают 6 цифр после команды

`bot.hears(/^\/init \d{6}$/gm, ctx => init(ctx))`
`bot.hears(/^\/toggle \d{6}$/gm, ctx => toggle(ctx))`
`bot.hears(/^\/list \d{6}$/gm, ctx => list(ctx))`

Команды других ботов не задействуют логику этого бота, но для обратного случая можно просто перенять механику префиксов

`/initBSUIR /toggleBSUIR /listBSUIR`
